name: Bump version

on:
  push:
    branches:
      - master
      
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
            
        - name: Get next version
          run: |
            full_version=$(grep -o "versionName.*" app/build.gradle.kts | awk '{ print $3 }' | tr -d \''"\')
            IFS='.' read -r -a array <<< "$full_version"
            version_name="$(date '+%Y.%-m.')"
            if [[ $full_version = $version_name* ]] ; then
              version_name+=$((array[2] + 1))
            else
              version_name+="1"
            fi
            version_name+=$((array[2] + 1))
            echo "VERSION_NAME=$version_name" >> $GITHUB_ENV
            version_code=$(grep "versionCode.*" app/build.gradle.kts | awk '{print $3}' | tr -d '\n')
            version_code=$((version_code + 1))
            echo "VERSION_CODE=$version_code" >> $GITHUB_ENV
            tag_name="v${version_name}"
            echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
            
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Bump version
          uses: chkfung/android-version-actions@v1.2.1
          with:
            gradlePath: app/build.gradle.kts
            versionCode: ${{env.VERSION_CODE}}
            versionName: ${{env.VERSION_NAME}}
            
        - name: Commit and push changes
          run: |
            git config user.name bogomolovaa
            git config user.email alllexander@gmail.com
            git commit -am "Release ${{env.TAG_NAME}}"
            git tag ${{env.TAG_NAME}}
            git push --atomic origin HEAD ${{env.TAG_NAME}}
