on:
  push:
    branches:
      - master
      
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Get next version name
          uses: reecetech/version-increment@2023.4.1
          id: version
          with:
            scheme: calver
            
        - name: Get next version code
          run: |
            version_code=$(grep "versionCode" app/build.gradle | awk '{print $2}' | tr -d '\n')
            version_code=$((version_code + 1))
            echo "VERSION_CODE=$version_code" >> $GITHUB_ENV
            
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Bump version
          uses: chkfung/android-version-actions@v1.2.1
          with:
            gradlePath: app/build.gradle
            versionCode: ${{steps.version.outputs.version}}
            versionName: ${{env.VERSION_CODE}}
            
        - name: Commit and push changes
          run: |
            git config user.name bogomolovaa
            git config user.email alllexander@gmail.com
            git commit -am "Bump version to ${{ steps.version.outputs.version }}"
            git push origin HEAD
