name: trigger gitlab

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        token: ${{ secrets.GITLAB_TOKEN }}
        project_id: 46693370
