name: trigger gitlab

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      run: |
        token=${{ secrets.GITLAB_TOKEN }}
        curl -X POST \
          --fail \
          -F token=$token \
          -F ref=master \
          https://gitlab.com/api/v4/projects/46693370/trigger/pipeline
